import type { Metadata } from "next";
import "../styles/globals.css";
import { raleway } from "./fonts";
import { cn } from "@/lib/utils";
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          "relative bg-background w-screen min-h-screen h-fit p-0 m-0",
          `${raleway.variable}`
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
