import type { Metadata } from "next";
import "../styles/globals.css";
import { raleway } from "./fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          "bg-background w-screen min-h-screen h-fit ",
          `${raleway.variable}`,
        )}
      >
        {children}
      </body>
    </html>
  );
}
